# Generated by Django 4.2.17 on 2025-01-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_released_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
